// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBecbzUJjKxvY6VM3h7T9_d7eYBrHWyC2o',
    appId: '1:142146516003:web:92e7144bc6cf6a253a2d96',
    messagingSenderId: '142146516003',
    projectId: 'tasks-58771',
    authDomain: 'tasks-58771.firebaseapp.com',
    storageBucket: 'tasks-58771.appspot.com',
    measurementId: 'G-KHJE6X3WCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-3Zw6RDRjWTZ6rHVyDWgjMl0ZRtUBQAY',
    appId: '1:142146516003:android:48558d95555223143a2d96',
    messagingSenderId: '142146516003',
    projectId: 'tasks-58771',
    storageBucket: 'tasks-58771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZZYoksSLTkTZ5Xs_qS29fZZboQT5eIw',
    appId: '1:142146516003:ios:7b8521fd7939298c3a2d96',
    messagingSenderId: '142146516003',
    projectId: 'tasks-58771',
    storageBucket: 'tasks-58771.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZZYoksSLTkTZ5Xs_qS29fZZboQT5eIw',
    appId: '1:142146516003:ios:7b8521fd7939298c3a2d96',
    messagingSenderId: '142146516003',
    projectId: 'tasks-58771',
    storageBucket: 'tasks-58771.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBecbzUJjKxvY6VM3h7T9_d7eYBrHWyC2o',
    appId: '1:142146516003:web:fe5aba4beafa52633a2d96',
    messagingSenderId: '142146516003',
    projectId: 'tasks-58771',
    authDomain: 'tasks-58771.firebaseapp.com',
    storageBucket: 'tasks-58771.appspot.com',
    measurementId: 'G-K9T5YDPKCD',
  );

}